# Generated by Django 6.0.3 on 2026-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
